'use client';
import {useEffect,useState} from 'react';
import {KeyRound,Clock3,ArrowRight,BookOpen,LockKeyhole,Sparkles,GraduationCap,ChevronLeft,Trophy,Lightbulb,Check,Download,RefreshCw,Copy,DoorOpen} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import Puzzle,{ProblemText,type VisibleQuestion} from '@/components/puzzle';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {courses} from '@/lib/catalog';
import SettingsPicker from '@/components/settings-picker';
import {difficultyLabels,type Difficulty,type Settings} from '@/lib/game-settings';
type Run={id:string;student:string;room:string|null;course:string;deadline:number;started:number;state:{settings?:Settings;solved:number[];hints:number[];score:number;stage:number;done:boolean;escaped:boolean};questions:VisibleQuestion[]};
async function api(body?:unknown,path=''){const r=await fetch('/api/game'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw new Error(d.error||'연결을 확인하고 다시 시도해 주세요.');return d;}
const names=['잠긴 교실','비밀 동아리실','마지막 방송실'];
function Picker({value,onChange}:{value:string;onChange:(s:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="course-select"><SelectValue/></SelectTrigger><SelectContent>{courses.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select>}
export default function Game(){const [screen,setScreen]=useState('home'),[course,setCourse]=useState('확률과 통계'),[unit,setUnit]=useState('all'),[difficulty,setDifficulty]=useState<Difficulty>('standard'),[code,setCode]=useState(''),[student,setStudent]=useState(''),[run,setRun]=useState<Run|null>(null),[active,setActive]=useState<number|null>(null),[answer,setAnswer]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now()),[rooms,setRooms]=useState<any[]>([]),[selected,setSelected]=useState(''),[records,setRecords]=useState<Run[]>([]);
async function act(body:any){setBusy(true);setError('');try{const d=await api(body);if(d.run){setRun(d.run);localStorage.setItem('last-bell-run',d.run.id);setScreen('game');}setMessage(d.feedback||'');return d;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function loadTeacher(sel=selected){setError('');try{const d=await api(undefined,'?teacher=1'+(sel?'&room='+encodeURIComponent(sel):''));setRooms(d.rooms);setRecords(d.records);}catch(e){setError((e as Error).message);}}
useEffect(()=>{const c=new URLSearchParams(location.search).get('code');if(c)setCode(c);const id=localStorage.getItem('last-bell-run');if(id)api(undefined,'?id='+encodeURIComponent(id)).then(d=>{if(d.run){setRun(d.run);if(!d.run.state.done)setScreen('game');}}).catch(()=>{});},[]);
useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
useEffect(()=>{if(run&&!run.state.done&&now>=run.deadline&&!busy){setActive(null);void act({action:'finish',id:run.id});}},[now,run?.id,run?.state.done]);
useEffect(()=>{if(screen!=='teacher')return;void loadTeacher();const t=setInterval(()=>void loadTeacher(),10000);return()=>clearInterval(t);},[screen,selected]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:'read_escape_progress',description:'Read the visible student game progress, score and remaining time.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({screen,score:run?.state.score??0,solved:run?.state.solved.length??0,remainingSeconds:run?Math.max(0,Math.ceil((run.deadline-Date.now())/1000)):900})},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[run,screen]);
const left=run?Math.max(0,Math.ceil((run.deadline-now)/1000)):900;const time=`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`;const s=run?.state;const q=run?.questions.find(q=>q.id===active);
function open(id:number){setActive(id);setAnswer('');setMessage('');setError('');}
function exportCsv(){const rows=[['학생 번호','점수','해결 문제','힌트','상태','단원','난이도'],...records.map(r=>[r.student,r.state.score,r.state.solved.length,r.state.hints.length,r.state.done?(r.state.escaped?'탈출 성공':'시간 종료'):'진행 중',r.state.settings?.unit??'이전 문제',r.state.settings?difficultyLabels[r.state.settings.difficulty]:'이전 문제'])];const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"').join(',')).join('\r\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=`수학탈출_${selected}.csv`;a.click();URL.revokeObjectURL(u);}
return <div className="app-shell"><header className="topbar"><button className="brand" onClick={()=>{setScreen('home');setActive(null);}}><span className="brand-icon"><KeyRound size={21}/></span><span>AFTER THE BELL<small>수학 교실 탈출</small></span></button><button className="quiet" onClick={()=>setScreen(screen==='teacher'?'home':'teacher')}><GraduationCap size={18}/>{screen==='teacher'?'게임으로 돌아가기':'교사용 공간'}</button></header>
{error&&<div className="error" role="alert">{error}</div>}
{screen==='home'&&<main className="home-grid"><section className="intro-scene"><img src="/classroom.png" alt="노을이 드는 텅 빈 교실, 칠판과 잠긴 사물함"/><div className="scene-shade"/><div className="scene-top"><span className="eyebrow">CHAPTER 01 · 방과 후의 초대</span><span className="pill"><Clock3 size={14}/>15 MIN</span></div><div className="intro-copy"><span className="tiny-rule">수학으로 여는 세 개의 문</span><h1>마지막 종이<br/>울리기 전에<span>.</span></h1><p>모두가 떠난 교실, 잠겨 버린 문.<br/>흩어진 단서를 풀고 마지막 열쇠를 찾아라.</p><div className="scene-stats"><span><KeyRound size={18}/>열쇠 3개</span><span><Sparkles size={18}/>최대 1,050점</span><span><Clock3 size={18}/>15분의 도전</span></div></div></section><section className="entry-panel"><span className="eyebrow amber">YOUR MISSION</span><h2>탈출 준비가 되었나요?</h2><p className="muted">배운 수학이 오늘의 탈출 도구가 됩니다.</p><label>탐험할 과목<Picker value={course} onChange={v=>{setCourse(v);setUnit("all");}}/></label><SettingsPicker course={course} unit={unit} difficulty={difficulty} onUnit={setUnit} onDifficulty={setDifficulty} disabled={!!code.trim()}/><label>수업 참여 코드 <span className="optional">선택</span><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="선생님이 알려준 8자리 코드" maxLength={8}/></label><label>학생 번호<input value={student} onChange={e=>setStudent(e.target.value)} placeholder="예: 30201" maxLength={20}/></label><button className="primary wide" disabled={busy||!student.trim()} onClick={()=>act({action:'start',course,code,student,unit,difficulty})}>{busy?'교실 문을 여는 중…':'15분 탈출 시작'}<ArrowRight size={19}/></button>{run&&!run.state.done&&<button className="quiet wide" onClick={()=>setScreen('game')}>진행 중인 탐험 이어하기</button>}<div className="mission-note"><Lightbulb size={20}/><p>정답을 맞히면 점수가 쌓여요.<br/><span>틀려도 감점 없이 다시 도전할 수 있어요.</span></p></div><div className="entry-bottom"><span>2022 개정 교육과정 · 과목별 개념 · 응용 문제</span><span>태블릿 · 모바일 지원</span></div></section></main>}
{screen==='game'&&run&&s&&!s.done&&<main className="play"><div className="play-heading"><div><span className="eyebrow">ROOM 0{s.stage+1} / 03</span><h1>{names[s.stage]}</h1></div><div className="hud"><span className={left<120?'urgent':''}><Clock3 size={19}/><b>{time}</b></span><span className="amber"><Sparkles size={18}/><b>{s.score}</b><small>PT</small></span></div></div><div className="play-grid"><section className={'room-scene room-'+s.stage}><img src="/classroom.png" alt={`${names[s.stage]}의 단서를 탐색하는 공간`}/><div className="room-overlay"/><span className="room-caption">{['칠판 위에 누군가의 메시지가 남아 있다.','책상 서랍에서 암호화된 기록을 발견했다.','사물함 뒤, 마지막 문을 여는 장치가 빛난다.'][s.stage]}</span><button className={'hotspot main-spot spot-'+s.stage+(s.solved.includes(s.stage*2)?' solved':'')} onClick={()=>open(s.stage*2)}><span>{s.solved.includes(s.stage*2)?<Check/>:<KeyRound/>}</span><b>{['칠판의 메시지','책상의 기록','사물함의 잠금'][s.stage]}</b><small>{s.solved.includes(s.stage*2)?'해결 완료':'필수 단서 · 100점'}</small></button><button disabled={!s.solved.includes(s.stage*2)} className="hotspot bonus-spot" onClick={()=>open(s.stage*2+1)}><span>{s.solved.includes(s.stage*2+1)?<Check/>:<Sparkles/>}</span><b>비밀 보관함</b><small>추가 도전 · 200점</small></button><span className="touch-note">빛나는 단서를 터치하세요</span></section><aside className="journal"><span className="eyebrow amber">EXPLORER'S NOTES</span><h2>나의 탐험 기록</h2><div className="identity"><BookOpen size={18}/><span>{run.course}<small>{run.student} 탐험가</small>{run.state.settings&&<small>{run.state.settings.unit==="all"?"전체 단원":run.state.settings.unit} · {difficultyLabels[run.state.settings.difficulty]}</small>}</span></div><div className="keys">{names.map((n,i)=><div key={n} className={s.solved.includes(i*2)?'earned':''}><KeyRound/><small>0{i+1}</small></div>)}</div><h3>이번 방의 미션</h3><button className="task-row" onClick={()=>open(s.stage*2)}>{s.solved.includes(s.stage*2)?<Check className="amber"/>:<LockKeyhole/>}<span>필수 단서 풀기<small>{run.questions[s.stage*2].topic}</small></span></button><button className="task-row" disabled={!s.solved.includes(s.stage*2)} onClick={()=>open(s.stage*2+1)}><Sparkles/><span>수학 응용 문제 풀기<small>선택 도전 · 추가 200점</small></span></button><p className="muted journal-tip">필수 단서를 풀면 다음 방으로 갈 수 있어요. 보너스 점수도 챙겨 볼까요?</p><button className="primary wide" disabled={busy||!s.solved.includes(s.stage*2)} onClick={()=>act({action:'next',id:run.id})}>{s.stage===2?'마지막 문 열기':'다음 방으로'}<ArrowRight size={18}/></button><small className="save-note">문제 해결 시 자동 저장 · 새로고침 후 이어하기</small></aside></div></main>}
{screen==='game'&&run&&s?.done&&<main className="result"><div className="result-glow"><Trophy size={54}/></div><span className="eyebrow amber">{s.escaped?'MISSION COMPLETE':'EXPLORATION COMPLETE'}</span><h1>{s.escaped?'교실 탈출 성공!':'오늘의 탐험 완료!'}</h1><p className="muted">{s.escaped?'스스로 풀어낸 수학이 잠긴 문을 열었어요.':'끝까지 도전한 기록과 획득한 점수가 남았어요.'}</p><div className="total">{s.score.toLocaleString()}<span>POINTS</span></div><div className="result-stats"><div><b>{s.solved.length}</b><span>해결한 문제</span></div><div><b>{s.solved.filter(i=>i%2===0).length}</b><span>찾아낸 열쇠</span></div><div><b>{s.hints.length}</b><span>사용한 힌트</span></div></div><div className="badge"><Sparkles size={20}/>{s.solved.length===6?'모든 단서를 찾은 마스터':s.escaped?'잠긴 문을 연 해결사':'용기 있게 도전한 탐험가'}</div><p className="save-note">{run.room?'점수와 풀이 기록을 수업방에 저장했습니다.':'연습 결과가 저장되었습니다.'}</p><details><summary>문제와 해설 돌아보기</summary>{run.questions.map(q=><div className="review" key={q.id}><b>{s.solved.includes(q.id)?'✓ ':''}{q.topic}</b><ProblemText question={q}/><span>정답 {q.answerText??q.answer}</span><ol>{(q.explanation??[q.hint]).map((step,i)=><li key={i}>{step}</li>)}</ol></div>)}</details><button className="primary" onClick={()=>{setScreen('home');setActive(null);}}>새로운 탐험 준비<ArrowRight size={18}/></button></main>}
{screen==='teacher'&&<main className="teacher"><span className="eyebrow amber">TEACHER'S DESK</span><h1>우리 반 탐험 현황</h1><p className="muted">수업방을 만들고, 학생들의 작은 성공을 함께 확인하세요.</p><div className="teacher-grid"><section className="panel"><h2>새 수업방 만들기</h2><label>출제 과목<Picker value={course} onChange={v=>{setCourse(v);setUnit("all");}}/></label><SettingsPicker course={course} unit={unit} difficulty={difficulty} onUnit={setUnit} onDifficulty={setDifficulty}/><p className="muted">15분 · 필수 3문제 + 보너스 3문제</p><button className="primary wide" disabled={busy} onClick={async()=>{const d=await act({action:'create',course,unit,difficulty});if(d){setSelected(d.code);void loadTeacher(d.code);}}}>수업방 생성<KeyRound size={18}/></button><p className="fine">20개 과목에서 대표 단원과 난이도를 선택할 수 있습니다. 전체 성취기준을 망라한 평가용 문제은행은 아닙니다.</p><a className="source" href="https://home.pen.go.kr/hscredit/cm/cntnts/cntntsView.do?cntntsId=3729&mi=17411" target="_blank" rel="noreferrer">2022 개정 과목 체계 참고 ↗</a></section><section className="panel"><div className="row-between"><h2>내 수업방</h2><button className="quiet" onClick={()=>loadTeacher()} aria-label="새로고침"><RefreshCw size={18}/></button></div>{rooms.length===0?<p className="muted">아직 수업방이 없습니다. 첫 탐험을 만들어 보세요.</p>:<div className="room-list">{rooms.map(r=><button key={r.code} className={selected===r.code?'selected':''} onClick={()=>setSelected(r.code)}><BookOpen size={18}/><span>{r.course}<small>{r.unit==='all'?'전체 단원':r.unit} · {difficultyLabels[r.difficulty as Difficulty]??'보통'}</small><small>{new Date(r.created).toLocaleDateString('ko-KR')}</small></span><b>{r.code}</b></button>)}</div>}</section></div>{selected&&<section className="panel results-panel"><div className="row-between"><div><span className="eyebrow">참여 코드</span><h2 className="code">{selected}</h2></div><div className="row"><button className="quiet" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/?code='+selected);setMessage('학생용 참여 링크를 복사했습니다.');}catch{setError('링크 복사가 지원되지 않습니다. 주소와 참여 코드를 전달해 주세요.');}}}><Copy size={17}/>참여 링크 복사</button><button className="quiet" onClick={exportCsv} disabled={!records.length}><Download size={17}/>엑셀용 CSV</button></div></div>{message&&<p role="status" className="amber">{message}</p>}<p className="fine">현재 비공개 미리보기입니다. 학생 기기 접속에는 사이트 공유 범위 설정이 필요합니다.</p><Table><TableHeader><TableRow>{['학생 번호','획득 점수','해결 문제','힌트','상태'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{records.map(r=><TableRow key={r.id}><TableCell>{r.student}</TableCell><TableCell className="amber">{r.state.score}점</TableCell><TableCell>{r.state.solved.length}/6</TableCell><TableCell>{r.state.hints.length}회</TableCell><TableCell>{r.state.done?(r.state.escaped?'탈출 성공':'탐험 종료'):`${r.state.stage+1}번째 방`}</TableCell></TableRow>)}</TableBody></Table>{!records.length&&<p className="empty">참여한 학생의 기록이 여기에 표시됩니다.</p>}<p className="save-note">10초마다 갱신 · 이 수업방을 만든 계정만 결과를 볼 수 있습니다.</p></section>}</main>}
<Puzzle open={active!==null&&!!run&&!run.state.done} onClose={()=>setActive(null)} question={q} solved={!!q&&!!s?.solved.includes(q.id)} time={time} score={s?.score??0} busy={busy} answer={answer} setAnswer={setAnswer} message={message} error={error} onAnswer={()=>{if(run&&q)void act({action:'answer',id:run.id,question:q.id,answer});}} onHint={()=>{if(run&&q)void act({action:'hint',id:run.id,question:q.id});}}/>
<footer><span>AFTER THE BELL</span><span>문제 하나, 한 걸음 더.</span></footer></div>}
