'use client';
import {useRef,useState} from 'react';
import {ArrowRight,Check,Clock3,KeyRound,Lightbulb,Sparkles,X} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import MathExpression from './math-expression';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import MathDiagram from './math-diagram';
import type {Diagram} from '@/lib/game-settings';
export type VisibleQuestion={format?:'choice'|'short';course?:string;choices?:{id:string;label:string}[];id:number;topic:string;prompt:string;formula?:string[];conditions?:string[];ask?:string;points:number;hint?:string;answer?:number;answerText?:string;explanation?:string[];diagram?:Diagram};
export function ProblemText({question:q}:{question:VisibleQuestion}){return <div className="problem-body">{q.course&&<p className="question-course">{q.course} · {q.format==='choice'?'오지선다형':'주관식'}</p>}<p className="problem-intro">{q.prompt}</p>{q.conditions&&<div className="given-conditions"><h3>주어진 조건</h3><ul>{q.conditions.map((c,i)=><li key={i}>{c}</li>)}</ul></div>}{!!q.formula?.length&&<div className="formula-panel">{q.formula.map((f,i)=><MathExpression key={i} source={f}/>)}</div>}{q.diagram&&<MathDiagram diagram={q.diagram}/ >}{q.ask&&<p className="problem-ask"><span>구할 값</span>{q.ask}</p>}{q.choices&&<ol className="review-choices" aria-label="보기">{q.choices.map((c,i)=><li key={c.id}>{['①','②','③','④','⑤'][i]} {c.label}</li>)}</ol>}</div>}
export default function Puzzle({open,onClose,question:q,solved,time,score,busy,answer,setAnswer,message,error,onAnswer,onHint}:{open:boolean;onClose:()=>void;question?:VisibleQuestion;solved:boolean;time:string;score:number;busy:boolean;answer:string;setAnswer:(s:string)=>void;message:string;error:string;onAnswer:()=>void;onHint:()=>void}){
 const [large,setLarge]=useState(false);const title=useRef<HTMLHeadingElement>(null);
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose();}}><DialogContent showCloseButton={false} className={'puzzle-reader'+(large?' reader-large':'')} onOpenAutoFocus={e=>{e.preventDefault();title.current?.focus();}}>
 <div className="reader-status"><span><KeyRound size={17}/>문제 풀이</span><div><span aria-label={'남은 시간 '+time}><Clock3 size={17}/><b>{time}</b></span><span className="reader-score"><Sparkles size={17}/>{score}점</span><button onClick={onClose} aria-label="문제 닫고 교실로 돌아가기"><X size={22}/></button></div></div>
 <div className="reader-heading"><div><div className="reader-labels"><span className={q&&q.id%2?'challenge-label':'basic-label'}>{q&&q.id%2?'응용 도전':'핵심 개념'}</span><span>{q?.points}점</span><span>단서 {q?String(q.id+1).padStart(2,'0'):''} / 06</span></div><DialogTitle ref={title} tabIndex={-1} className="reader-title">{q?.topic}</DialogTitle><DialogDescription className="reader-description">조건을 읽고, 수학으로 잠금을 풀어 보세요.</DialogDescription></div><div className="type-controls" aria-label="문제 글자 크기"><button type="button" aria-pressed={!large} onClick={()=>setLarge(false)}>가</button><button type="button" aria-label="문제 글자 크게" aria-pressed={large} onClick={()=>setLarge(true)}>가+</button></div></div>
 <div className="reader-columns"><section className="problem-sheet" aria-label="문제">{q&&<ProblemText question={q}/>}<div className="problem-footnote">{q&&q.id%2?'앞선 개념을 새로운 조건에 적용해 보세요.':'핵심 개념을 떠올리며 차근차근 풀어 보세요.'}</div></section>
 <aside className="answer-sheet" aria-label="답안과 풀이 도움">{solved?<div className="answer-success"><Check size={24}/><h3>잠금 해제 완료</h3><p>정답 <strong>{q?.answerText??q?.answer}</strong></p></div>:<form onSubmit={e=>{e.preventDefault();onAnswer();}}>{q?.format==='choice'?<fieldset className="choice-fieldset"><legend>정답을 하나 선택하세요.</legend><RadioGroup value={answer} onValueChange={setAnswer} disabled={busy} aria-label="오지선다 답안">{q.choices?.map((choice,i)=><label className={'answer-choice'+(answer===choice.id?' is-selected':'')} key={choice.id} htmlFor={'choice-'+q.id+'-'+choice.id}><RadioGroupItem id={'choice-'+q.id+'-'+choice.id} value={choice.id}/><span>{['①','②','③','④','⑤'][i]}</span><strong>{choice.label}</strong></label>)}</RadioGroup></fieldset>:<><label htmlFor="math-answer">나의 답</label><input id="math-answer" value={answer} onChange={e=>setAnswer(e.target.value)} inputMode="text" autoComplete="off" autoCapitalize="off" spellCheck={false} maxLength={80} placeholder="정수 · 소수 · 분수" aria-describedby="answer-format"/><p id="answer-format" className="answer-format">예: 12, −3, 0.5, 1/2<br/>단위 없이 값만 입력하세요.</p></>}<button className="primary wide" disabled={busy||!answer.trim()}>{busy?'확인 중…':'정답 확인'}<KeyRound size={18}/></button><p className="score-rule">첫 시도 · 힌트 없이 정답이면 +25점<br/>오답이어도 감점은 없어요.</p></form>}
 {message&&<p className={'reader-feedback'+(solved?' is-correct':'')} role="status">{message}</p>}{error&&<p className="reader-error" role="alert">{error}</p>}
 {q?.hint&&!solved?<div className="reader-hint"><h3><Lightbulb size={18}/>생각의 실마리</h3><p>{q.hint}</p></div>:!solved&&<button className="hint-button" disabled={busy} onClick={onHint}><Lightbulb size={19}/>힌트 보기<span>기본 점수 유지</span></button>}
 {solved&&q?.explanation&&<div className="worked-solution"><h3>풀이 과정</h3><ol>{q.explanation.map((step,i)=><li key={i}><span>{i+1}</span><p>{step}</p></li>)}</ol></div>}{solved&&<button className="primary wide" onClick={onClose}>교실로 돌아가기<ArrowRight size={18}/></button>}
 </aside></div></DialogContent></Dialog>;
}
