import {db} from '@/db/raw';
import {courses,questions} from '@/lib/questions-v2';
import {numericAnswer} from '@/lib/numeric-answer';
export const dynamic='force-dynamic';
type Run={id:string;owner:string;room:string|null;student:string;course:string;started:number;state:string;version:number};
type State={questionVersion?:number;solved:number[];hints:number[];attempts:Record<string,number>;score:number;stage:number;done:boolean;escaped:boolean};
const fresh=():State=>({questionVersion:2,solved:[],hints:[],attempts:{},score:0,stage:0,done:false,escaped:false});
function identity(r:Request){const id=r.headers.get('oai-authenticated-user-id');if(!id)throw new Error('로그인 후 이용해 주세요.');return id;}
function view(r:Run){
 const s=JSON.parse(r.state) as State;const done=s.done||Date.now()>=r.started+900000;
 return {...r,owner:undefined,state:{...s,done},deadline:r.started+900000,
 questions:questions(r.course,s.questionVersion??1).map(({answer,hint,explanation,answerText,...q})=>{
 const solved=s.solved.includes(q.id);return {...q,
 hint:done||s.hints.includes(q.id)||solved?hint:undefined,
 answer:done||solved?answer:undefined,answerText:done||solved?answerText:undefined,
 explanation:done||solved?explanation:undefined};})};
}
const out=(x:unknown,status=200)=>Response.json(x,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:Request){try{const owner=identity(req);const url=new URL(req.url);if(url.searchParams.has('teacher')){const rs=await db().prepare('SELECT * FROM rooms WHERE owner=? ORDER BY created DESC').bind(owner).all();const selected=url.searchParams.get('room');let records:unknown[]=[];if(selected){const room=await db().prepare('SELECT code FROM rooms WHERE code=? AND owner=?').bind(selected,owner).first();if(!room)return out({error:'수업방 접근 권한이 없습니다.'},403);const found=await db().prepare('SELECT * FROM runs WHERE room=? ORDER BY student').bind(selected).all<Run>();records=found.results.map(view);}return out({rooms:rs.results,records});}const id=url.searchParams.get('id');if(!id)return out({run:null});const r=await db().prepare('SELECT * FROM runs WHERE id=? AND owner=?').bind(id,owner).first<Run>();return out({run:r?view(r):null});}catch(e){return out({error:(e as Error).message},400);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return out({error:'요청 출처를 확인하세요.'},403);const owner=identity(req);const b:any=await req.json();if(b.action==='create'){if(!courses.includes(b.course))throw new Error('과목을 선택하세요.');const code=crypto.randomUUID().replaceAll('-','').slice(0,8).toUpperCase();await db().prepare('INSERT INTO rooms (code,owner,course,created) VALUES (?,?,?,?)').bind(code,owner,b.course,Date.now()).run();return out({code});}
if(b.action==='start'){let course=b.course;let room=null;if(b.code){const found=await db().prepare('SELECT * FROM rooms WHERE code=?').bind(String(b.code).trim().toUpperCase()).first<{code:string;course:string}>();if(!found)throw new Error('참여 코드를 확인해 주세요.');course=found.course;room=found.code;}if(!courses.includes(course))throw new Error('과목을 선택하세요.');const student=String(b.student||'연습').trim();if(student.length>20||!student)throw new Error('학생 번호를 20자 이내로 입력하세요.');if(room){const old=await db().prepare('SELECT * FROM runs WHERE owner=? AND room=? ORDER BY started DESC LIMIT 1').bind(owner,room).first<Run>();if(old)return out({run:view(old)});}const r:Run={id:crypto.randomUUID(),owner,room,student,course,started:Date.now(),state:JSON.stringify(fresh()),version:0};await db().prepare('INSERT INTO runs (id,owner,room,student,course,started,state,version) VALUES (?,?,?,?,?,?,?,?)').bind(r.id,owner,room,student,course,r.started,r.state,0).run();return out({run:view(r)});}
const r=await db().prepare('SELECT * FROM runs WHERE id=? AND owner=?').bind(b.id,owner).first<Run>();if(!r)throw new Error('진행 기록을 찾지 못했습니다.');const s=JSON.parse(r.state) as State;let feedback='';if(Date.now()>=r.started+900000){s.done=true;feedback='15분이 종료되었습니다. 획득한 점수는 저장됩니다.';}else if(!s.done){const qs=questions(r.course,s.questionVersion??1);if(b.action==='answer'||b.action==='hint'){const q=qs.find(q=>q.id===b.question);if(!q||Math.floor(q.id/2)!==s.stage)throw new Error('현재 방의 단서를 선택하세요.');if(q.id%2===1&&!s.solved.includes(q.id-1))throw new Error('필수 단서를 먼저 해결하세요.');if(b.action==='hint'){if(!s.hints.includes(q.id))s.hints.push(q.id);}else if(!s.solved.includes(q.id)){const value=numericAnswer(b.answer);if(value===null)throw new Error('정수, 소수 또는 분수로 입력하세요. 예: -3, 0.5, 1/2');s.attempts[q.id]=(s.attempts[q.id]||0)+1;if(Math.abs(value-q.answer)<=1e-9){s.solved.push(q.id);const points=q.points+(s.attempts[q.id]===1&&!s.hints.includes(q.id)?25:0);s.score+=points;feedback=`정답! +${points}점을 획득했어요.`;}else feedback='아직 잠금이 풀리지 않았어요. 다시 생각해 보세요. 점수는 줄지 않습니다.';}}
else if(b.action==='next'){if(!s.solved.includes(s.stage*2))throw new Error('필수 단서를 풀어 열쇠를 획득하세요.');if(s.stage===2){s.done=true;s.escaped=true;}else s.stage++;}else if(b.action==='finish'){s.done=true;}else throw new Error('올바른 동작을 선택하세요.');}
const saved=await db().prepare('UPDATE runs SET state=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(s),r.id,r.version).run();if(!saved.meta.changes)return out({error:'진행 상황이 변경되었습니다. 새로고침 후 다시 시도하세요.'},409);return out({run:view({...r,state:JSON.stringify(s),version:r.version+1}),feedback});}catch(e){console.error('game request',e);return out({error:(e as Error).message},400);}}
